# Generated by Django 4.2.2 on 2023-07-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_password_alter_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
    ]
